EXP_NAME: cf_night_ctkt_e-6_19c
SOURCE: Cityscapes
DATA_DIRECTORY_SOURCE: /gpfswork/rech/vrk/ulz82cw/datasets/cityscapes
DATA_LIST_SOURCE: /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/cityscapes_list/{}.txt
TARGETS:
    - ACDC
    - ACDC
    - ACDC
    - ACDC
DATA_DIRECTORY_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
DATA_LIST_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
NUM_WORKERS: 4
NUM_CLASSES: 19
EXP_ROOT: /gpfsscratch/rech/vrk/ulz82cw/expe
EXP_ROOT_SNAPSHOT: /gpfsscratch/rech/vrk/ulz82cw/expe
TEST:
  MODE: single
  RESTORE_FROM:
    - /gpfswork/rech/vrk/ulz82cw/expe/ncda/cf_night_ctkt_e-6_19c/model.pth
  INPUT_SIZE_TARGET:
    - 1024
    - 512
  OUTPUT_SIZE_TARGET:
    - 1024
    - 512
  SET_TARGET:
    - fog_val
    - night_val
    - rain_val
    - snow_val
  INFO_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
