EXP_NAME: gci_mapillary_lrb_2.5e-4_7c_640x320
SOURCE: GTA
DATA_DIRECTORY_SOURCE: /gpfswork/rech/vrk/ulz82cw/datasets/GTA5
TARGETS:
    - Mapillary
DATA_DIRECTORY_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/datasets/mapillary
DATA_LIST_TARGET:
    -
NUM_WORKERS: 4
NUM_CLASSES: 7
EXP_ROOT: /gpfsscratch/rech/vrk/ulz82cw/expe
EXP_ROOT_SNAPSHOT: /gpfsscratch/rech/vrk/ulz82cw/expe
TEST:
  MODE: single
  RESTORE_FROM:
    - /gpfswork/rech/vrk/ulz82cw/expe/ncda/gci_mapillary_lrb_2.5e-4_7c_sr/model.pth
  INPUT_SIZE_TARGET:
    - 640
    - 320
  OUTPUT_SIZE_TARGET:
    - 640
    - 320
  SET_TARGET:
    - validation
