EXP_NAME: gta2cityscapes_19c_640x320
SOURCE: GTA
DATA_DIRECTORY_SOURCE: /gpfswork/rech/vrk/ulz82cw/datasets/GTA5
TARGETS:
    - Cityscapes
    - ACDC
    - ACDC
    - ACDC
    - ACDC
DATA_DIRECTORY_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/datasets/cityscapes
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
DATA_LIST_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/cityscapes_list/{}.txt
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
NUM_WORKERS: 4
NUM_CLASSES: 19
EXP_ROOT: /gpfsscratch/rech/vrk/ulz82cw/expe
EXP_ROOT_SNAPSHOT: /gpfsscratch/rech/vrk/ulz82cw/expe
TEST:
  MODE: single
  RESTORE_FROM:
    - /gpfswork/rech/vrk/ulz82cw/expe/ncda/gta_cityscapes_19c_sr/model.pth
  INPUT_SIZE_TARGET:
    - 640
    - 320
  OUTPUT_SIZE_TARGET:
    - 640
    - 320
  INFO_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/cityscapes_list/info.json
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json        
  SET_TARGET:
    - val
    - fog_val
    - night_val
    - rain_val
    - snow_val
