EXP_NAME: cfn_rain_cctkt_e-6_19c
SOURCE: Cityscapes
DATA_DIRECTORY_SOURCE: /gpfswork/rech/vrk/ulz82cw/datasets/cityscapes
DATA_LIST_SOURCE: /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/cityscapes_list/{}.txt
TARGETS:
    - ACDC
DATA_DIRECTORY_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/datasets/ACDC
DATA_LIST_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/{}.txt
NUM_WORKERS: 4
NUM_CLASSES: 19
EXP_ROOT: /gpfsscratch/rech/vrk/ulz82cw/expe
EXP_ROOT_SNAPSHOT: /gpfsscratch/rech/vrk/ulz82cw/expe
TRAIN:
  INPUT_SIZE_SOURCE:
    - 1024
    - 512
  INPUT_SIZE_TARGET:
    - 1024
    - 512
  DISTILL:
    LAMBDA: 1.0e-6
    FEAT: True
    KL_LOGITS: True
    KL_LAMBDA: 1.0e-6
  DA_METHOD: AdvEnt
  SET_SOURCE: train
  MODEL: DeepLabv2CTKT
  RESTORE_FROM: /gpfswork/rech/vrk/ulz82cw/expe/ncda/cf_night_cctkt_e-6_19c/model.pth
  RESTORE_D_MAIN: /gpfswork/rech/vrk/ulz82cw/expe/ncda/cf_night_cctkt_e-6_19c/model_D_main.pth
  RESTORE_D_AUX: /gpfswork/rech/vrk/ulz82cw/expe/ncda/cf_night_cctkt_e-6_19c/model_D_aux.pth
  MULTI_LEVEL: True
  SET_TARGET:
    - rain_train
  INFO_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
  MAX_ITERS: 120000
  EARLY_STOP: 60000
TEST:
  MODE: best
  SET_TARGET:
    - rain_val
  INFO_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/projects/CDA/cda/dataset/acdc_list/info.json
  INPUT_SIZE_TARGET:
    - 1024
    - 512
  OUTPUT_SIZE_TARGET:
    - 1024
    - 512
  SNAPSHOT_MAXITER: 60000
