EXP_NAME: gta2cityscapes2idd2mapillary_baseline_pretrained
TARGETS:
    - Cityscapes
    - IDD
    - Mapillary
DATA_DIRECTORY_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/datasets/cityscapes
    - /gpfswork/rech/vrk/ulz82cw/datasets/IDD/IDD_Segmentation
    - /gpfswork/rech/vrk/ulz82cw/datasets/mapillary
DATA_LIST_TARGET:
    - /gpfswork/rech/vrk/ulz82cw/projects/MuHDi-private/muhdi/dataset/cityscapes_list/{}.txt
    - /gpfswork/rech/vrk/ulz82cw/projects/MuHDi-private/muhdi/dataset/idd_list/{}.txt
    -
NUM_WORKERS: 4
NUM_CLASSES: 7
TEST:
  MODE: single
  RESTORE_FROM:
    - ../../pretrained_models/gta2cityscapes2idd2mapillary_baseline_pretrained/model.pth
  INPUT_SIZE_TARGET:
    - 640
    - 320
  OUTPUT_SIZE_TARGET:
    - 640
    - 320
  SET_TARGET:
    - val
    - val
    - validation
