EXP_NAME: gta2cityscapes_advent_pretrained
TARGETS:
    - Cityscapes
    - IDD
DATA_DIRECTORY_TARGET:
    - ../../data/cityscapes
    - ../../data/IDD
DATA_LIST_TARGET:
    - ../../muhdi/dataset/cityscapes_list/{}.txt
    - ../../muhdi/dataset/idd_list/{}.txt
NUM_WORKERS: 4
NUM_CLASSES: 7
TEST:
  MODE: single
  RESTORE_FROM:
    - ../../pretrained_models/gta2cityscapes_advent_pretrained/model.pth
  INPUT_SIZE_TARGET:
    - 640
    - 320
  OUTPUT_SIZE_TARGET:
    - 640
    - 320
  SET_TARGET:
    - val
    - val
