EXP_NAME: gta2cityscapes_advent
SOURCE: GTA
DATA_DIRECTORY_SOURCE: ../../data/GTA5
TARGETS:
    - Cityscapes
DATA_DIRECTORY_TARGET:
    - ../../data/cityscapes
DATA_LIST_TARGET:
    - ../muhdi/dataset/cityscapes_list/{}.txt
NUM_WORKERS: 4
NUM_CLASSES: 7
TRAIN:
  INPUT_SIZE_SOURCE:
    - 640
    - 320
  INPUT_SIZE_TARGET:
    - 640
    - 320
  MODEL: DeepLabv2
  RESTORE_FROM: ../../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  SET_TARGET:
    - train
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
  MAX_ITERS: 240000
  EARLY_STOP: 120000
TEST:
  MODE: best
  INPUT_SIZE_TARGET:
    - 640
    - 320
  OUTPUT_SIZE_TARGET:
    - 640
    - 320
  SNAPSHOT_MAXITER: 120000
